# Generated by Django 5.1.1 on 2024-09-17 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_receipt_purchasedatetime_receipt_purchasedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='purchaseDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='purchaseTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
